export const playlists = [
    {
        "id": "257022316",
        "title": "MTP - Hey Maa Durge - hindi - Jai Durga Maa",
        "subtitle": "34.5K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/mtp-hey-maa-durge-hindi-jai-durga-maa/gQAVg2c,ZtLfemJ68FuXsA__",
        "image": "https://c.saavncdn.com/editorial/logo/MTPHeyMaaDurgehindiJaiDurgaMaa_20211005144956.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "257022316",
            "isWeekly": "false",
            "listname": "MTP - Hey Maa Durge - hindi - Jai Durga Maa",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "34536",
            "fan_count": "28,540"
        },
        "button_tooltip_info": []
    },
    {
        "id": "47599074",
        "title": "Now Trending",
        "subtitle": "29.5K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/now-trending/BECHl0fsh08_",
        "image": "https://c.saavncdn.com/editorial/NowTrending_20220914084524.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "47599074",
            "isWeekly": "false",
            "listname": "Now Trending",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "29452",
            "fan_count": "20,266"
        },
        "button_tooltip_info": []
    },
    {
        "id": "824476960",
        "title": "Weekly Jukebox - Udit Narayan &amp; Alka Yagnik hindi",
        "subtitle": "1.2K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/weekly-jukebox-udit-narayan-alka-yagnik-hindi/6xRsHOrDNfRuOxiEGmm6lQ__",
        "image": "https://c.saavncdn.com/editorial/hindi-cluster_15_20240902002831.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "824476960",
            "isWeekly": "false",
            "listname": "Weekly Jukebox - Udit Narayan &amp; Alka Yagnik hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "1249",
            "fan_count": "0"
        },
        "button_tooltip_info": []
    },
    {
        "id": "257184865",
        "title": "MTP - Jai Ambe Maharani - hindi - Jai Durga Maa",
        "subtitle": "6.2K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/mtp-jai-ambe-maharani-hindi-jai-durga-maa/r9rVNJ4mdQ3uCJW60TJk1Q__",
        "image": "https://c.saavncdn.com/editorial/logo/MTPJaiAmbeMaharanihindiJaiDurgaMaa_20200611075440.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "257184865",
            "isWeekly": "false",
            "listname": "MTP - Jai Ambe Maharani - hindi - Jai Durga Maa",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "6193",
            "fan_count": "5,116"
        },
        "button_tooltip_info": []
    },
    {
        "id": "108237829",
        "title": "Weekly Jukebox - Bollywood Romantic hindi",
        "subtitle": "237.4K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/weekly-jukebox-bollywood-romantic-hindi/ge28leNugkOO0eMLZZxqsA__",
        "image": "https://c.saavncdn.com/editorial/hindi-cluster_29_20240902004518.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "108237829",
            "isWeekly": "false",
            "listname": "Weekly Jukebox - Bollywood Romantic hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "237389",
            "fan_count": "18,574"
        },
        "button_tooltip_info": []
    },
    {
        "id": "163514096",
        "title": "Top JioTunes - Hindi",
        "subtitle": "1.3M Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/top-jiotunes-hindi/AZNZNH1EwNjfemJ68FuXsA__",
        "image": "https://c.saavncdn.com/editorial/TopJioTunesHindi_20230622054323.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "163514096",
            "isWeekly": "false",
            "listname": "Top JioTunes - Hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "1320403",
            "fan_count": "874,752"
        },
        "button_tooltip_info": []
    },
    {
        "id": "62556959",
        "title": "Directors Cut - Imtiaz Ali",
        "subtitle": "4.8K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/directors-cut-imtiaz-ali/I,5EKlBQQyc_",
        "image": "https://c.saavncdn.com/editorial/DirectorsCutImtiazAli_20180616172801.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "62556959",
            "isWeekly": "false",
            "listname": "Directors Cut - Imtiaz Ali",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "4799",
            "fan_count": "4,734"
        },
        "button_tooltip_info": []
    },
    {
        "id": "170998710",
        "title": "Top JioTunes - Bollywood Retro - Hindi",
        "subtitle": "115.1K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/top-jiotunes-bollywood-retro-hindi/AoMVjuC9sjluOxiEGmm6lQ__",
        "image": "https://c.saavncdn.com/editorial/TopJioTunesBollywoodRetroHindi_20230622054313.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "170998710",
            "isWeekly": "false",
            "listname": "Top JioTunes - Bollywood Retro - Hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "115085",
            "fan_count": "18,990"
        },
        "button_tooltip_info": []
    },
    {
        "id": "42663291",
        "title": "Chand Sifarish",
        "subtitle": "15.7K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/chand-sifarish/-EmxwhCLM9w_",
        "image": "https://c.saavncdn.com/editorial/ChandSifarish_20230824052134.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "42663291",
            "isWeekly": "false",
            "listname": "Chand Sifarish",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "15730",
            "fan_count": "14,074"
        },
        "button_tooltip_info": []
    },
    {
        "id": "257208542",
        "title": "MTP - Vighnaharta Ganesh - hindi - Jai Shree Ganesha",
        "subtitle": "15.4K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/mtp-vighnaharta-ganesh-hindi-jai-shree-ganesha/cPDd6gS8aEjc1EngHtQQ2g__",
        "image": "https://c.saavncdn.com/editorial/logo/MTPVighnahartaGaneshhindiJaiShreeGanesha_20210907171234.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "257208542",
            "isWeekly": "false",
            "listname": "MTP - Vighnaharta Ganesh - hindi - Jai Shree Ganesha",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "15424",
            "fan_count": "12,716"
        },
        "button_tooltip_info": []
    },
    {
        "id": "257202610",
        "title": "MTP - Om Namah Shivay - hindi - Jai Shiv Shankar",
        "subtitle": "67.7K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/mtp-om-namah-shivay-hindi-jai-shiv-shankar/jPV1FR8whUluOxiEGmm6lQ__",
        "image": "https://c.saavncdn.com/editorial/logo/MTPOmNamahShivayhindiJaiShivShankar_20200611075405.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "257202610",
            "isWeekly": "false",
            "listname": "MTP - Om Namah Shivay - hindi - Jai Shiv Shankar",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "67679",
            "fan_count": "56,753"
        },
        "button_tooltip_info": []
    },
    {
        "id": "86644393",
        "title": "Long Drive Bollywood",
        "subtitle": "3.4K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/long-drive-bollywood/9Bf,CJ4x6kc_",
        "image": "https://c.saavncdn.com/editorial/logo/FILTRLongDriveBollywood_86644393_20160818.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "86644393",
            "isWeekly": "false",
            "listname": "Long Drive Bollywood",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "3393",
            "fan_count": "2,957"
        },
        "button_tooltip_info": []
    },
    {
        "id": "53490462",
        "title": "Feel Good Bollywood",
        "subtitle": "5K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/feel-good-bollywood/ykPbHBQFUJU_",
        "image": "https://c.saavncdn.com/editorial/logo/FeelGoodBollywood_20200622170731.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "53490462",
            "isWeekly": "false",
            "listname": "Feel Good Bollywood",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "4952",
            "fan_count": "4,804"
        },
        "button_tooltip_info": []
    },
    {
        "id": "157002182",
        "title": "Weekly Jukebox - Kumar Sanu hindi",
        "subtitle": "13K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/weekly-jukebox-kumar-sanu-hindi/O8TyiLqZitTc1EngHtQQ2g__",
        "image": "https://c.saavncdn.com/editorial/hindi-cluster_66_20240902010024.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "157002182",
            "isWeekly": "false",
            "listname": "Weekly Jukebox - Kumar Sanu hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "12964",
            "fan_count": "12,751"
        },
        "button_tooltip_info": []
    },
    {
        "id": "83440110",
        "title": "Dancing Divas",
        "subtitle": "1.6K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/dancing-divas/kYpwEbwNYWA_",
        "image": "https://c.saavncdn.com/editorial/logo/DancingDivas_83440110_20160421.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "83440110",
            "isWeekly": "false",
            "listname": "Dancing Divas",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "1622",
            "fan_count": "1,503"
        },
        "button_tooltip_info": []
    },
    {
        "id": "257198371",
        "title": "MTP - Jai Bholenath - hindi - Jai Shiv Shankar",
        "subtitle": "12.1K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/mtp-jai-bholenath-hindi-jai-shiv-shankar/Zmcx-rI4QlgGSw2I1RxdhQ__",
        "image": "https://c.saavncdn.com/editorial/logo/MTPJaiBholenathhindiJaiShivShankar_20200611070102.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "257198371",
            "isWeekly": "false",
            "listname": "MTP - Jai Bholenath - hindi - Jai Shiv Shankar",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "12057",
            "fan_count": "10,692"
        },
        "button_tooltip_info": []
    },
    {
        "id": "266497173",
        "title": "Top JioTunes - Hindustani - Hindi",
        "subtitle": "138.3K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/top-jiotunes-hindustani-hindi/OCE917iSOsMwkg5tVhI3fw__",
        "image": "https://c.saavncdn.com/editorial/logo/TopJioTunesHindustaniClassicalHindi_20190418100152.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "266497173",
            "isWeekly": "false",
            "listname": "Top JioTunes - Hindustani - Hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "138263",
            "fan_count": "137,761"
        },
        "button_tooltip_info": []
    },
    {
        "id": "42443196",
        "title": "When Actors Sing",
        "subtitle": "9.1K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/when-actors-sing/tCKs,IB,6Bw_",
        "image": "https://c.saavncdn.com/editorial/WhenActorsSing_20230321174332.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "42443196",
            "isWeekly": "false",
            "listname": "When Actors Sing",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "9095",
            "fan_count": "7,812"
        },
        "button_tooltip_info": []
    },
    {
        "id": "108237764",
        "title": "Weekly Jukebox - 90s Unwind hindi",
        "subtitle": "13.8K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/weekly-jukebox-90s-unwind-hindi/ELKR7jkfsKHufxkxMEIbIw__",
        "image": "https://c.saavncdn.com/editorial/hindi-cluster_44_20240902004907.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "108237764",
            "isWeekly": "false",
            "listname": "Weekly Jukebox - 90s Unwind hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "13812",
            "fan_count": "13,700"
        },
        "button_tooltip_info": []
    },
    {
        "id": "257218775",
        "title": "MTP - Mere Ram - hindi - Jai Shri Ram",
        "subtitle": "75.3K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/mtp-mere-ram-hindi-jai-shri-ram/b6AFSx-Sh4XuCJW60TJk1Q__",
        "image": "https://c.saavncdn.com/editorial/logo/MTPMereRamhindiJaiShriRam_20200611065846.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "257218775",
            "isWeekly": "false",
            "listname": "MTP - Mere Ram - hindi - Jai Shri Ram",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "75316",
            "fan_count": "70,403"
        },
        "button_tooltip_info": []
    },
    {
        "id": "78261328",
        "title": "Juhi Ka Jaadu",
        "subtitle": "3.2K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/juhi-ka-jaadu/6dZ,jKr9ayI_",
        "image": "https://c.saavncdn.com/editorial/logo/JuhiKaJaadu_20211101152031.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "78261328",
            "isWeekly": "false",
            "listname": "Juhi Ka Jaadu",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "3225",
            "fan_count": "3,164"
        },
        "button_tooltip_info": []
    },
    {
        "id": "170968270",
        "title": "Top JioTunes - Bollywood Romantic - Hindi",
        "subtitle": "475.2K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/top-jiotunes-bollywood-romantic-hindi/3XQBTVdiJc5uOxiEGmm6lQ__",
        "image": "https://c.saavncdn.com/editorial/logo/TopJioTunesBollywoodRomanticHindi_20210208181852.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "170968270",
            "isWeekly": "false",
            "listname": "Top JioTunes - Bollywood Romantic - Hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "475190",
            "fan_count": "464,507"
        },
        "button_tooltip_info": []
    },
    {
        "id": "77076833",
        "title": "Timeless Ghazals",
        "subtitle": "48K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/timeless-ghazals/Kdb2rW52fiE_",
        "image": "https://c.saavncdn.com/editorial/logo/TimelessGhazals_20211215062059.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "77076833",
            "isWeekly": "false",
            "listname": "Timeless Ghazals",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "47989",
            "fan_count": "29,766"
        },
        "button_tooltip_info": []
    },
    {
        "id": "157002084",
        "title": "Weekly Jukebox - Bollywood 2000s hindi",
        "subtitle": "7.8K Followers",
        "header_desc": "",
        "type": "playlist",
        "perma_url": "https://www.jiosaavn.com/featured/weekly-jukebox-bollywood-2000s-hindi/r1qVjkfJoZPufxkxMEIbIw__",
        "image": "https://c.saavncdn.com/editorial/hindi-cluster_21_20191103132441.jpg",
        "language": "",
        "year": "",
        "play_count": "",
        "explicit_content": "0",
        "list_count": "0",
        "list_type": "",
        "list": "",
        "more_info": {
            "listid": "157002084",
            "isWeekly": "false",
            "listname": "Weekly Jukebox - Bollywood 2000s hindi",
            "firstname": "JioSaavn",
            "song_count": "",
            "follower_count": "7758",
            "fan_count": "7,277"
        },
        "button_tooltip_info": []
    }
]